//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package fr.dudie.directorysync;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.os.Handler;
import android.util.Log;
import android.view.KeyEvent;
import android.view.View;
import android.view.ViewGroup.LayoutParams;
import android.widget.ListView;
import com.googlecode.androidannotations.api.BackgroundExecutor;
import com.googlecode.androidannotations.api.SdkVersionHelper;
import fr.dudie.directorysync.R.id;
import fr.dudie.directorysync.R.layout;
import fr.dudie.directorysync.service.FileExplorerServiceMock_;

public final class RemoteFileList_
    extends RemoteFileList
{

    private Handler handler_ = new Handler();

    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        setContentView(layout.act_remote_file_list);
    }

    private void init_(Bundle savedInstanceState) {
        fileExplorer = FileExplorerServiceMock_.getInstance_(this);
    }

    private void afterSetContentView_() {
        remoteFilesList = ((ListView) findViewById(id.remote_files));
        ((FileExplorerServiceMock_) fileExplorer).afterSetContentView_();
        setup();
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        afterSetContentView_();
    }

    @Override
    public boolean onKeyDown(int keyCode, KeyEvent event) {
        if (((SdkVersionHelper.getSdkInt()< 5)&&(keyCode == KeyEvent.KEYCODE_BACK))&&(event.getRepeatCount() == 0)) {
            onBackPressed();
        }
        return super.onKeyDown(keyCode, event);
    }

    public static RemoteFileList_.IntentBuilder_ intent(Context context) {
        return new RemoteFileList_.IntentBuilder_(context);
    }

    @Override
    public void hideLoad() {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                try {
                    RemoteFileList_.super.hideLoad();
                } catch (RuntimeException e) {
                    Log.e("RemoteFileList_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

    @Override
    public void showLoad() {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                try {
                    RemoteFileList_.super.showLoad();
                } catch (RuntimeException e) {
                    Log.e("RemoteFileList_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

    @Override
    public void loadRemoteFiles() {
        BackgroundExecutor.execute(new Runnable() {


            @Override
            public void run() {
                try {
                    RemoteFileList_.super.loadRemoteFiles();
                } catch (RuntimeException e) {
                    Log.e("RemoteFileList_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, RemoteFileList_.class);
        }

        public Intent get() {
            return intent_;
        }

        public RemoteFileList_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (context_ instanceof Activity) {
                ((Activity) context_).startActivityForResult(intent_, requestCode);
            } else {
                context_.startActivity(intent_);
            }
        }

    }

}
